from __future__ import unicode_literals

import pdfkit
import frappe, os, io
from frappe.utils import get_files_path, now_datetime
from frappe import _, _dict,msgprint

from frappe.utils.pdf import get_pdf,cleanup
from frappe.core.doctype.access_log.access_log import make_access_log
#from PyPDF2 import PdfFileReader, PdfFileWriter
from pypdf import PdfReader, PdfWriter
no_cache = 1

base_template_path = "templates/www/printview.html"
standard_format = "templates/print_formats/standard.html"


def get_pdf_to_print(doctype, name, printformat, output, letterhead):
	return frappe.get_print(doctype, name, printformat, as_pdf = True, output = output, no_letterhead=letterhead)

def merge_first_pdf_with_second(output, output1):
	for page in output1.pages:
		output.addPage(page)

	return output

def get_pdf_by_url(filepath, output):
	file_path = get_full_path(filepath)
	with open(file_path, "rb") as fileobj:
		filedata = fileobj.read()

	reader = PdfReader(io.BytesIO(filedata), strict=False)
	for page in reader.pages:
		output.addPage(page)

	return output

@frappe.whitelist()
def create_workorder_pdf(doctype, name, format, no_letterhead=0):
	"""
	Concatenate multiple docs as PDF .

	Returns a PDF compiled by concatenating multiple documents. The documents
	can be from a single DocType or multiple DocTypes

	Note: The design may seem a little weird, but it exists exists to
		ensure backward compatibility. The correct way to use this function is to
		pass a dict to doctype as described below

	NEW FUNCTIONALITY
	=================
	Parameters:
	doctype (dict):
		key (string): DocType name
		value (list): of strings of doc names which need to be concatenated and printed
	name (string):
		name of the pdf which is generated
	format:
		Print Format to be used

	Returns:
	PDF: A PDF generated by the concatenation of the mentioned input docs

	OLD FUNCTIONALITY - soon to be deprecated
	=========================================
	Parameters:
	doctype (string):
		name of the DocType to which the docs belong which need to be printed
	name (string or list):
		If string the name of the doc which needs to be printed
		If list the list of strings of doc names which needs to be printed
	format:
		Print Format to be used

	Returns:
	PDF: A PDF generated by the concatenation of the mentioned input docs
	"""

	import json
	output = PdfWriter()

	if not isinstance(doctype, dict):
		
		#format = json.loads(format)
		#for ff in format:
			#if ff.get('__checked'):
				# Concatenating pdf files
		output = frappe.get_print(doctype, name, 'Job Card Print PDF' , as_pdf = True, output = output, no_letterhead=no_letterhead)
		frappe.local.response.filename = "{doctype}.pdf".format(doctype=doctype.replace(" ", "-").replace("/", "-"))
	#frappe.local.response.filecontent = read_multi_pdf(output)
	#frappe.local.response.type = "pdf"
	drg = frappe.get_value('Work Order', {"name":name}, ["drawing_file"] )

	fname= read_multi_pdf(output,drg)
	
	with open(fname, "rb") as fileobj:
		filedata = fileobj.read()
	frappe.local.response.filename = "{}.pdf".format(name)

	frappe.local.response.filecontent = filedata
	frappe.local.response.type = "pdf"

# @frappe.whitelist()
# def create_workorder_A3_pdf(doctype, name, format, no_letterhead=0):
# 	"""
# 	Concatenate multiple docs as PDF .

# 	Returns a PDF compiled by concatenating multiple documents. The documents
# 	can be from a single DocType or multiple DocTypes

# 	Note: The design may seem a little weird, but it exists exists to
# 		ensure backward compatibility. The correct way to use this function is to
# 		pass a dict to doctype as described below

# 	NEW FUNCTIONALITY
# 	=================
# 	Parameters:
# 	doctype (dict):
# 		key (string): DocType name
# 		value (list): of strings of doc names which need to be concatenated and printed
# 	name (string):
# 		name of the pdf which is generated
# 	format:
# 		Print Format to be used

# 	Returns:
# 	PDF: A PDF generated by the concatenation of the mentioned input docs

# 	OLD FUNCTIONALITY - soon to be deprecated
# 	=========================================
# 	Parameters:
# 	doctype (string):
# 		name of the DocType to which the docs belong which need to be printed
# 	name (string or list):
# 		If string the name of the doc which needs to be printed
# 		If list the list of strings of doc names which needs to be printed
# 	format:
# 		Print Format to be used

# 	Returns:
# 	PDF: A PDF generated by the concatenation of the mentioned input docs
# 	"""

# 	import json
# 	output = PdfFileWriter()

# 	if not isinstance(doctype, dict):
		
# 		#format = json.loads(format)
# 		#for ff in format:
# 			#if ff.get('__checked'):
# 				# Concatenating pdf files
# 		output = frappe.get_print(doctype, name, 'Job Card Print A3 PDF' , as_pdf = True, output = output, no_letterhead=no_letterhead)
# 		frappe.local.response.filename = "{doctype}.pdf".format(doctype=doctype.replace(" ", "-").replace("/", "-"))
# 	#frappe.local.response.filecontent = read_multi_pdf(output)
# 	#frappe.local.response.type = "pdf"
# 	drg = frappe.get_value('Work Order', {"name":name}, ["drawing_file"] )

# 	fname= read_multi_pdf(output,drg)
	
# 	with open(fname, "rb") as fileobj:
# 		filedata = fileobj.read()
# 	frappe.local.response.filename = "{}.pdf".format(name)

# 	frappe.local.response.filecontent = filedata
# 	frappe.local.response.type = "pdf"

@frappe.whitelist(allow_guest=True)
def open_workorder_print(name, drg,doctype, no_letterhead = 0):
	import json
	output = PdfWriter()
	empcode = frappe.get_value('Employee',{"user_id": frappe.session.user} )
	employee =frappe.get_doc("Employee", empcode)
	itemno =''
	wono =frappe.get_doc(doctype, name)
	if doctype == 'Work Order':
		itemno = ""
	frappe.publish_realtime("print_wo_cumulative", dict(progress=[1, 1]), user=frappe.session.user)

	if drg:
		fname = drg
		file_path = get_files_path(*fname.split("/private/files/", 1)[1].split("/"), is_private=1)
		with open(file_path, "rb") as fileobj:
			filedata = fileobj.read()

		reader = PdfReader(io.BytesIO(filedata), strict=False)
		# if doctype=='Work Order':
		# 	filetomerge = get_watermarkforwo_pdf(name, mode = "Portrait")
		# # elif doctype=='BOM':
		# # 	filetomerge = get_watermarkforbom_pdf(employee, name,wono.item, mode = "Portrait")
		# watermark_file = PdfFileReader(io.BytesIO(filetomerge), strict = False)
		# watermark_page = watermark_file.getPage(0)
		if doctype == 'Work Order':
			filetomerge_l = get_watermarkforwo_pdf(employee, name,wono.date,wono.drawing_no,wono.production_item,wono.qty,wono.sales_order_no,wono.delivery_date,itemno, mode = "Landscape")
		# elif doctype=='BOM':
		# 	filetomerge_l = get_watermarkforbom_pdf(employee, name,wono.item,mode = "Landscape")
		watermark_file_l = PdfReader(io.BytesIO(filetomerge_l), strict = False)
		watermark_page_l = watermark_file_l.getPage(0)

		for page in reader.pages:
			if page.mediaBox.getWidth() > 600:
				page.mergePage(watermark_page_l)
			# else:
			# 	page.mergePage(watermark_page)
			output.addPage(page)

			#output.appendPagesFromReader(reader)
	fname = os.path.join("/tmp", "frappe-pdf-{0}.pdf".format(frappe.generate_hash()))
	output.write(open(fname,"wb"))
	return fname

def get_watermarkforwo_pdf(employee, name,date,drgno,item,qty,sono,deliverydate,itemno, mode):
	today = now_datetime()
	body= """
	<html>
	<head>
		<meta name="pdfkit-orientation" content="{9}"/>
	</head>
	</html>
	""".format(mode)
#<td>Security Level: CONFIDENTIAL</td>

	footer = """
    <html>
	<head>
		<meta name="pdfkit-orientation" content="{9}"/>
	</head>
	<body>
	<table style='width:100%; font-size:12px; color: red'>
	<tbody>
	<tr>
	<td style='font-size:10px;'></td>
	<td>WO NO & Date: {1} & {2}</td>
	<td>DRG NO: {10}</td>
	<td>DELIVERY DATE: {7}</td>
	<td>{5} - #{7}</td>
	<td>Qty: {4} Nos</td>
	<td>PART NO: {3} </td>
	</tr>
	</tbody>
	</table>
	</body>
    </html>
    """.format(employee.employee_name, name, date.strftime('%d/%m/%Y'),item,qty,sono, today.strftime('%d/%m/%Y'),deliverydate.strftime('%d/%m/%Y'),itemno, mode,drgno)

	fname = os.path.join("/tmp", "frappe-pdf-{0}.html".format(frappe.generate_hash()))
	with open(fname, "wb") as f:
		f.write(footer.encode("utf-8"))
		
	options = {}
	options["margin-bottom"] = "5mm"
	options["footer-html"] = fname

	filedata = pdfkit.from_string(body, False, options=options)
	return filedata

@frappe.whitelist(allow_guest=True)
def sales_order_cumulative(name, fname):
	with open(fname, "rb") as fileobj:
		filedata = fileobj.read()

	frappe.local.response.filename = "{}.pdf".format(name)

	frappe.local.response.filecontent = filedata
	frappe.local.response.type = "pdf"

def read_multi_pdf(output,drg):
	# Get the content of the merged pdf files
	fname = os.path.join("/tmp", "frappe-pdf-{0}.pdf".format(frappe.generate_hash()))
	output.write(open(fname,"wb"))

	with open(fname, "rb") as fileobj:
		filedata1 = fileobj.read()

	if drg.find('private') != -1:
		file_path = get_files_path(*drg.split("/private/files/", 1)[1].split("/"), is_private=1)
	else:
		file_path = get_files_path(*drg.split("/files/", 1)[1].split("/"), is_private=0)

	with open(file_path, "rb") as fileobj:
		filedata = fileobj.read()

	reader = PdfReader(io.BytesIO(filedata), strict=False)
	watermark_file = PdfReader(io.BytesIO(filedata1), strict = False)
	watermark_page = watermark_file.getPage(0)
	
	output1 = PdfWriter()
	for page in reader.pages:
		#if page.mediaBox.getWidth() > 600:
		#	page.mergePage(watermark_page_l)
		#else:
		page.mergePage(watermark_page)
		output1.addPage(page)

	#output.appendPagesFromReader(reader)
	fname1 = os.path.join("/tmp", "frappe-pdf-{0}.pdf".format(frappe.generate_hash()))
	output1.write(open(fname1,"wb"))
	return fname1

	#return filedata


@frappe.whitelist()
def download_multi_pdf(doctype, name, count, format, no_letterhead=0):

	import json
	output = PdfWriter()

	if not isinstance(doctype, dict):
		
		format = json.loads(format)
		for ff in format:
			if ff.get('__checked'):
				# Concatenating pdf files
				output = frappe.get_print(doctype, name, ff.get('name'), as_pdf = True, output = output, no_letterhead=no_letterhead)
		frappe.local.response.filename = "{doctype}.pdf".format(doctype=doctype.replace(" ", "-").replace("/", "-"))
	else:
		for doctype_name in doctype:
			for doc_name in doctype[doctype_name]:
				try:
					output = frappe.get_print(doctype_name, doc_name, format, as_pdf = True, output = output, no_letterhead=no_letterhead)
				except Exception:
					frappe.log_error("Permission Error on doc {} of doctype {}".format(doc_name, doctype_name))
		frappe.local.response.filename = "{}.pdf".format(name)

	frappe.local.response.filecontent = read_si_multi_pdf(output)
	frappe.local.response.type = "pdf"
	# printcount = 0;
	# printcount = count + 1;
	frappe.db.set_value('Sales Invoice', name, 'print_count', 1)


def read_si_multi_pdf(output):
	# Get the content of the merged pdf files
	fname = os.path.join("/tmp", "frappe-pdf-{0}.pdf".format(frappe.generate_hash()))
	output.write(open(fname,"wb"))

	with open(fname, "rb") as fileobj:
		filedata = fileobj.read()

	return filedata





def get_full_path(file_name):
	"""Returns file path from given file name"""
	file_path = file_name

	if "/" not in file_path:
		file_path = "/files/" + file_path

	if file_path.startswith("/private/files/"):
		file_path = get_files_path(*file_path.split("/private/files/", 1)[1].split("/"), is_private=1)

	elif file_path.startswith("/files/"):
		file_path = get_files_path(*file_path.split("/files/", 1)[1].split("/"))

	elif file_path.startswith("http"):
		pass

	elif not self.file_url:
		frappe.throw(_("There is some problem with the file url: {0}").format(file_path))

	return file_path

